const airlines_information = [
	{
		site: "https://www.alaskaair.com",
		code: "AS",
		alliance: "OW",
		phone: "+1 800 252 75 22",
		name: "Alaska Airlines",
		usName: null,
		__clazz: "com.r9.harmony.httpd.mobileapis.AirlineMobile",
		defaultName: null,
		logoURL: "https://www.kayak.com/rimg/provider-logos/airlines/v/AS.png?crop=false&width=108&height=92&fallback=default2.png&_v=7e7c4110616a97db4d99676711cb7247",
	},
	{
		site: "https://www.AA.com",
		code: "AA",
		alliance: "OW",
		phone: "+1 800 433 7300",
		name: "American Airlines",
		usName: null,
		__clazz: "com.r9.harmony.httpd.mobileapis.AirlineMobile",
		defaultName: null,
		logoURL: "https://www.kayak.com/rimg/provider-logos/airlines/v/AA.png?crop=false&width=108&height=92&fallback=default2.png&_v=8c6d0e40bdbaad9c51e737b05c12347f",
	},
	{
		site: "https://www.delta.com",
		code: "DL",
		alliance: "ST",
		phone: "+1 888 750 3284",
		name: "Delta",
		usName: null,
		__clazz: "com.r9.harmony.httpd.mobileapis.AirlineMobile",
		defaultName: null,
		logoURL: "https://www.kayak.com/rimg/provider-logos/airlines/v/DL.png?crop=false&width=108&height=92&fallback=default1.png&_v=02a9af26513d796d51e54147426d15b5",
	},
	{
		site: "https://www.jetblue.com",
		code: "B6",
		alliance: "none",
		phone: "1-801-449-2525",
		name: "JetBlue",
		usName: null,
		__clazz: "com.r9.harmony.httpd.mobileapis.AirlineMobile",
		defaultName: null,
		logoURL: "https://www.kayak.com/rimg/provider-logos/airlines/v/B6.png?crop=false&width=108&height=92&fallback=default1.png&_v=1d9c582b6d8f9aebe5ff965c9bb916ee",
	},
	{
		site: "https://www.united.com",
		code: "UA",
		alliance: "SA",
		phone: "+1 800 864 8331",
		name: "United Airlines",
		usName: null,
		__clazz: "com.r9.harmony.httpd.mobileapis.AirlineMobile",
		defaultName: null,
		logoURL: "https://www.kayak.com/rimg/provider-logos/airlines/v/KN.png?crop=false&width=108&height=92&fallback=default1.png&_v=95b5a7fc9053b0fac604c9a27d1cda6f",
	},
	{
		site: "https://www.virginatlantic.com",
		code: "VS",
		alliance: "ST",
		phone: "+44 (0) 7481 339184",
		name: "Virgin Atlantic",
		usName: null,
		__clazz: "com.r9.harmony.httpd.mobileapis.AirlineMobile",
		defaultName: null,
		logoURL: "https://www.kayak.com/rimg/provider-logos/airlines/v/VS.png?crop=false&width=108&height=92&fallback=default2.png&_v=8900d8c3ff946cc0dc3eaa32e75e154e",
	},
];

export default airlines_information;
